### PR TITLE
parking-orbit

### PR DESCRIPTION
**Pull request by WillieRuemmele**
### What does this PR do?
parking orbits `plugin-config` as V1.4 to avoid a V3 ahead of V2(used for `sf`)
### What issues does this PR fix or reference?
@W-10743800@

### CODE REVIEW

**Review by peternhale — APPROVED** [review]

**Comment by iowillhoit** [comment]
## QA Notes

Switching plugin-config to CoreV3 has some odd behavior. While most of this is handled alright in the CLI (E.G. I can still create a scratch org with my default DevHub even if it is not set in `~/.sf/config.json`) but there are some edge cases

### `config:list`

**Before (V2)**

```
Name                   Value       Location
─────────────────────  ──────────  ────────
defaultdevhubusername  hub         Global
defaultusername        qa-6-alias  Global
```

**After (V3)**

🟡 New `sf` values displayed instead of `defaultdevhubusername` and `defaultusername`. This seems to be intended but could be confusing for `sfdx` users 

```
Name           Value      Location
 ────────────── ────────── ────────
 target-dev-hub hub        Global
 target-org     qa-6-alias Global
```

### `config:list --json`

🟡 Same. New `sf` values `target-org` and `target-dev-hub` used instead of `defaultdevhubusername` and `defaultusername`

### `config:get --json`

🟢 Error as expect, keys match (Note: v3 does have a new `context` key)

### `config:get defaultusername defaultdevhubusername instanceUrl`

**Before (V2)**

```
Name                   Value       Success
─────────────────────  ──────────  ───────
defaultusername        qa-6-alias  true
defaultdevhubusername  hub         true
instanceUrl                        true
```

**After (V3)**

🔴 Values undefined. `get` does not look up values from `~/.sdfx/config.json` (note that if you use `config:get target-org target-dev-hub` they are displayed). If `config:list` is smart enough to look up old values from `~/.sfdx`, then `config:get` should be also. 
🔴 Success is `true` in this situation? 

```
 Name                  Value     Success
 ───────────────────── ───────── ───────
 defaultusername       undefined true
 defaultdevhubusername undefined true
 instanceUrl           undefined true
```

### `config:get defaultusername defaultdevhubusername instanceUrl --json`

**Before (V2)**

```
{
  "status": 0,
  "result": [
    {
      "key": "defaultusername",
      "location": "Global",
      "value": "qa-6-alias",
      "path": "/Users/ewillhoit/.sfdx/sfdx-config.json"
    },
    {
      "key": "defaultdevhubusername",
      "location": "Global",
      "value": "hub",
      "path": "/Users/ewillhoit/.sfdx/sfdx-config.json"
    },
    {
      "key": "instanceUrl"
    }
  ]
}
```

**After (V3)**

🔴 Not returning values, acting as if they were undefined. Same as above, using `target-org` and `target-dev-hub` will return values. Worth noting that the missing keys when a value is `undefined` is how this has been working. See `instanceUrl` in the V2 output above.

```
{
  "status": 0,
  "result": [
    {
      "key": "defaultusername",
      "deprecated": true
    },
    {
      "key": "defaultdevhubusername",
      "deprecated": true
    },
    {
      "key": "instanceUrl",
      "deprecated": false
    }
  ]
}
```

### `config:set foo=bar --json`

🟢 JSON error correct for setting config outside of project

### `config:set -g foo=bar --json`

🟢 JSON error correct for "Unknown config name"

### `config:set -g disableTelemetry=true --json`

🟢 JSON correct for setting allowed config name
🔴 Setting a value in V3 duplicates old values into `~/.sf/config.json`

Steps to reproduce
- Make sure `defaultdevhubusername` and `defaultusername` are set in `~/.sfdx/config.json`
- Open up your `~/.sf/config.json`
- Clear and save the config (`{}`)
- In the v3 branch
  - Run `bin/run config:list`
    - Note `defaultdevhubusername` and `defaultusername` are not listed
  - Run `bin/run config:set disableTelemetry=true -g`
  - Run `bin/run config:list` again
    - Note `defaultdevhubusername` and `defaultusername` have been copied to the `sf` config

### `config:set maxQueryLimit=99 --json` 

🟢 JSON correct for setting local value
🟢 local value takes precidence over global with `config:list`

### `config:set -g maxQueryLimit=70 disableTelemetry=true --json`

🟢 Can set multiple values 

### `config:unset --json`

🟢 JSON error correct when not passing a value to unset

### `config:unset maxQueryLimit --json`

🟢 JSON error correct for trying to unset a global variable without the `-g` flag

### `config:unset maxQueryLimit --json`

🟢 JSON error correct for unsetting local value
🟢 Value properly unset

### `config:unset -g maxQueryLimit --json`

🟢 JSON correct for unsetting value
🟢 Value properly unset
🟡 Unsetting a value that doesn't exist returns successful? I don't disagree with the `exitCode 0` but I would at least expect a warning in the logs. 

### `config:unset -g maxQueryLimit disableTelemetry --json`

🟢 JSON correct for unsetting value
🟢 Multiple values unset properly

**Comment by iowillhoit** [comment]
`success = true` still doesn't make sense for undefined get values. Honestly not sure why we include that in the table... It's not included in the JSON output

**Comment by iowillhoit** [comment]
### QA Notes
Local config is not listed for `defaultusername`
JSON still has `sf` values
Setting an `sf` value still updates `sfdx` values 

### Replication
- `sfdx plugins:link` (plugin-config)
- `git clone git@github.com:trailheadapps/dreamhouse-lwc.git org--config--dreamhouse`
- `cd org--config--dreamhouse`
- `sfdx force:org:create -s -f config/project-scratch-def.json`
- `sfdx config:list`
  - `sf` values hidden 🟢
  - `defaultusername` is still "Global" 🔴
  - Note: local `./.sfdx/sfdx-config.json` does have correct value
- `sfdx config:list --json`
  - json output still has `sf` values 🔴
- `sfdx force:org:list` and `sfdx force:org:dsplay` have correct username 🟢
- `sfdx config:set target-org=THE_USERNAME_FROM_ORG_CREATE_ABOVE`
  - Throws error about unknown config (exit code 1) 🟢
  - `sfdx config:list`
    - `set target-org` still updates "Local" `defaultusername` value even though command throws error 🔴

**Review by iowillhoit — APPROVED** [review]

**Comment by iowillhoit** [comment]
New updates work great!

**Pull request merged**
